//
//  DisplayImageDetailWorker.swift
//  UnitTestUseNumbleQuickTutorial
//
//  Created by Papon Supamongkonchai on 3/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

class DisplayImageDetailWorker {
    
    var service: DisplayImageDetailService!
    
    init(with aService: DisplayImageDetailService) {
        service = aService
    }
    // MARK: Business Logic
    func getImageDisplay(imageRandomId: String,aCompletion: @escaping (DisplayImageDetailModels.DetailModels.Response?) -> Void, fail: @escaping (_ error: String?) -> ()) {
        
        service.requestImageDisplayDetails(imageRandomId: imageRandomId) { aJSON in
            aCompletion(DisplayImageDetailModels.DetailModels.Response(json: aJSON))
        } aFailure: { error in
            fail(error)
        }

    }
}
