//
//  DisplayImageDetailPresenter.swift
//  UnitTestUseNumbleQuickTutorial
//
//  Created by Papon Supamongkonchai on 3/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayImageDetailPresentationLogic
{
  func presentSomething(response: DisplayImageDetail.Something.Response)
}

class DisplayImageDetailPresenter: DisplayImageDetailPresentationLogic
{
  weak var viewController: DisplayImageDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DisplayImageDetail.Something.Response)
  {
    let viewModel = DisplayImageDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
