//
//  DisplayImageDetailInteractor.swift
//  UnitTestUseNumbleQuickTutorial
//
//  Created by Papon Supamongkonchai on 3/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayImageDetailBusinessLogic {
    func requestDisplayImage(request: DisplayImageDetailModels.DetailModels.Request)
    func getExtraNameText() -> String
}

protocol DisplayImageDetailDataStore {
    //var name: String { get set }
}

class DisplayImageDetailInteractor: DisplayImageDetailBusinessLogic, DisplayImageDetailDataStore {
    var presenter: DisplayImageDetailPresentationLogic?
    var worker: DisplayImageDetailWorker = DisplayImageDetailWorker(with: DisplayImageDetailService())
    
    // MARK: Do something
    func requestDisplayImage(request: DisplayImageDetailModels.DetailModels.Request) {
        self.presenter?.presentStartLoading()
        worker.getImageDisplay(imageRandomId: request.imageID,aCompletion: { responseModel in
            self.presenter?.presentStopLoading()
            self.presenter?.presentDisplayImage(response: responseModel)
        }, fail: { error in
            self.presenter?.presentStopLoading()
            self.presenter?.presentError()
        })
        
    }
    
    func getExtraNameText() -> String {
        return "This name is real person from website picsum"
    }
}
