//
//  DisplayImageDetailPresenter.swift
//  UnitTestUseNumbleQuickTutorial
//
//  Created by Papon Supamongkonchai on 3/11/2565 BE.
//  Copyright (c) 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayImageDetailPresentationLogic {
    func presentDisplayImage(response: DisplayImageDetailModels.DetailModels.Response?)
    func presentStartLoading()
    func presentStopLoading()
    func presentError()
}

class DisplayImageDetailPresenter: DisplayImageDetailPresentationLogic {
    weak var viewController: DisplayImageDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentDisplayImage(response: DisplayImageDetailModels.DetailModels.Response?) {
        let viewModel = DisplayImageDetailModels.DetailModels.ViewModel(author: response?.author ?? "",
                                                                        width: response?.width ?? "",
                                                                        height: response?.height ?? "",
                                                                        urlImage: response?.downloadUrl ?? "")
        viewController?.displayDisplayImage(viewModel: viewModel)
    }
    
    func presentStartLoading() {
        viewController?.displayStartLoading()
    }
    
    func presentStopLoading() {
        viewController?.displayStopLoading()
    }
    
    func presentError() {
        viewController?.displayError()
    }
}
